### ISSUE TITLE
AttributeError: module 'imgaug' has no attribute 'imshow'

### ISSUE THREAD

**Issue by pmleffers** [aleju/imgaug-doc#2]
Using first example: 

import imageio
import imgaug as ia
%matplotlib inline

image = imageio.imread("https://upload.wikimedia.org/wikipedia/en/7/7d/Lenna_%28test_image%29.png")

print("Original:")
ia.imshow(image)

Original:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-dc8ac8489320> in <module>()
      6 
      7 print("Original:")
----> 8 ia.imshow(image)

AttributeError: module 'imgaug' has no attribute 'imshow'

**Comment by aleju** [comment]
Are you using an outdated version? `imgaug.imshow()` was added in one of the last versions

**Comment by pmleffers** [comment]
Thanks for the reply! I found a workaround for my situation, I merely copied the function from the library and ran it within my code and works great.
